language: php
php:
- '5.6'
- '7.0'
- '7.1'

before_script:
- composer install --dev --no-interaction
script:
- mkdir -p build/logs
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- travis_retry php vendor/bin/coveralls -v
notifications:
  slack:
    secure: ufIuxpCrnWq3muP9PxhTl2+2+hVpLP7tlo6cJHC55JubIDzRomPONL8hLv9bgXgZ/NFnz1Z9CgLal0/BYgNDlYx3tyx7qhawAMqm3QGNTt9zJOMmzo1o07yGs8XoHGorqkejR9QljGB2e4pC9bj8lNX51TxnXeY0TJdqlJgFeuchQXUAfH7iosNxlEgNu2SddaAm5QFqt9z5Vgmg45fXIojOnSoMpYzoQECJ2xNwLkz4xhM4yiIjvXCc1X3mAAm0AsQxtKYz8Epiv73OanJGkLguM++k+jpp8lemdZxTjfKcqv79XLa6Dcsdqll8Y5sHURpyzip7xNSfOXq65aaJSEyJc0DZ2a11vhp3uNazdtG4E45W5epbYPxmF3bUAjTkozH83GJKduMhoMystzvZRWUN31fPBADGRLJ3TgpRlYy1RpdvjTBZQc/y8+CcpMjzMSiHEl66TfMi7xaxoae87DYS/gEWTSdqRGe107LpTaGvvOQLB9NWIdyrM223K03++cBIBfVx/k/FyWVAqFo68hnnN4lTg6fMyDH0yot7emkOwqvqiyvxCILt9euv2qt0oSCn6w6snrSgpLpnaus0TcUxLg+7v5pou6yQ0qdpQhUSTvVdIjUaBANiv1+z5r7WFdxezLZOy/HjrqunNXZE2mWSm0XL+iEVpB7Wl2dWy9A=
