language: php
php:
- '5.6'
- '7.0'
- '7.1'
before_script:
- composer install --dev --no-interaction
script:
- mkdir -p build/logs
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
- travis_retry php vendor/bin/coveralls -v
notifications:
  slack:
    secure: oPZlkP1JEke+jcyeg1x171FspDIKSvw4juOgaXcoerGj6ZVJzbh6ip3Sdr8GBan9C+o9PsLZMkNh1NgihHv037auCi66tdVr0VcRNHG38P52H0TeevaaS1X6j/+BENSuiLqjBxLIpeEAnkBKn/AULs/jtEjCx8XsM9gJXaxAn8i5eu9b87AvUyY2E4Rzo8LutBozlrBdxeKGryHthhdfbg5oFBf0kARpSz91eMxjiVip/E++SS2IMmyCqYxpmnKaCq1tsHN9pn1p1Bg+i35TZaBY2Mi7u1EG0HVcXemVY0fLvqEMG6qxHx+W1zSdE1Ci4ODWCBV3RsWBeMw8K7Xw+U7EctaAtItX5eqQjv4nk4SifJN3sXygfSaZvtbjKxQezoLEPrn8EgeV48zgNJj/ThRUhd+6AjRHIBQkwZCH2qqxPmOkzivOQ0Awbo/Y77pEIePh/Zv7Q4KPR3EHo3ylzlWPAauLxCj0a5shmvnmFYQ8WEZIQ+t6wfPRkpAHJyu6jLlubGbGR9CeSoBrqRDVnDou3i4JXToY1rqgUOqXHvLeUYoB6xE9kenZupBnKrRAvSzxQeTytmQApSUKVZhRiuUQIpaY3NfYQ/XwgspsCBxfWRWwfugioi9Q/YhDUqwnrK7gc17Hhpz1zMtHF2B6vkuUeqPGnc0/2qcCm0qdZss=
